#ifndef _CERT_BROAN_IOTDEV_H
#define _CERT_BROAN_IOTDEV_H

#ifdef CERT_BROAN_IOTDEV_INIT
const char broan_iotdev_ca_cert[] =
	"-----BEGIN CERTIFICATE-----\n" \
	"MIIDwTCCAqmgAwIBAgIUYOI77pP1Yv4s9o1Rzuxec6YciLowDQYJKoZIhvcNAQEL\n" \
	"BQAwcDELMAkGA1UEBhMCVFMxDTALBgNVBAgMBFRlc3QxDTALBgNVBAcMBFRlc3Qx\n" \
	"DTALBgNVBAoMBFRlc3QxDTALBgNVBAsMBFRlc3QxDTALBgNVBAMMBFRlc3QxFjAU\n" \
	"BgkqhkiG9w0BCQEWB2FAYS5jb20wHhcNMjAwNTA2MDQwMzQwWhcNMjUwNTA1MDQw\n" \
	"MzQwWjBwMQswCQYDVQQGEwJUUzENMAsGA1UECAwEVGVzdDENMAsGA1UEBwwEVGVz\n" \
	"dDENMAsGA1UECgwEVGVzdDENMAsGA1UECwwEVGVzdDENMAsGA1UEAwwEVGVzdDEW\n" \
	"MBQGCSqGSIb3DQEJARYHYUBhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\n" \
	"AQoCggEBAOK7+PiDFcP/w64vzBBkH6GE9fAVOKs+JL7VEvvncSmrljzxJU6bzl75\n" \
	"lPM85JuHZUvt5ypzwUSzsRvbXVXk5yVHa48nwrTpElakTT1ktj2RW/Zdacwh71h5\n" \
	"yTGsbT/09nMRE4ATujx6cQqCx/0CZzKHmwoi/XDSGDyIKX8m67AGb/oxYI9IcQ3K\n" \
	"1JKIj8ONPxaObYYAPDtSGDVaa2uRas2E09OrKAh4KaGLuBmtgSu7mF5L4/cSmAUu\n" \
	"HMwOTgYjbcbP5E5VBbM6Zw2kmBOCyo4zPGfR336xkgo3i+jyT7/XUaZLYdKu/xhc\n" \
	"J75O04fM4feIVjqKWa9qdDQKMdLWFpcCAwEAAaNTMFEwHQYDVR0OBBYEFMcXtazY\n" \
	"HnEgDC5wma+ggsSSYqslMB8GA1UdIwQYMBaAFMcXtazYHnEgDC5wma+ggsSSYqsl\n" \
	"MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAFtQFHnJreTK2Tt3\n" \
	"C9MVW7kHUdeo+rg/TnLj833vy69UugmnGJLc5gzi3ozQe+YvhIgCpXj/fCW/FS8M\n" \
	"FDFVXdhpRGAyA8AF3l2o1Y7xcD9C5hZetACWL4J9RwQsPpW6nPNbQEJgzHGh+OeA\n" \
	"sv3wE5+as1s/QmgVcOgc1vYbQwtUrbelaNlVb+TQqJLLM9rQXdOtARRSiYcNzf+2\n" \
	"BmVlP4Oy1DhqseD3EUhy7KrcFjkOo8jaZ+IC7b4L+wQs+0+AH/+CGHhDYn+/Qn15\n" \
	"6SShnt+6Z+uPvj4jeWsVUatA+6skKaqBdvm7f4kBP0lLlfpiriutVjo0p+8SfK8z\n" \
	"kIqedTw=\n" \
	"-----END CERTIFICATE-----\n";

const char broan_iotdev_client_cert[] =
	"-----BEGIN CERTIFICATE-----\n" \
	"MIID1TCCAr2gAwIBAgIUZPne2XKPlq/S/eyhEIHJLucJknAwDQYJKoZIhvcNAQEL\n" \
	"BQAwcDELMAkGA1UEBhMCVFMxDTALBgNVBAgMBFRlc3QxDTALBgNVBAcMBFRlc3Qx\n" \
	"DTALBgNVBAoMBFRlc3QxDTALBgNVBAsMBFRlc3QxDTALBgNVBAMMBFRlc3QxFjAU\n" \
	"BgkqhkiG9w0BCQEWB2FAYS5jb20wHhcNMjAwNTA5MTIwOTAwWhcNMjUwNTA4MTIw\n" \
	"OTAwWjB+MQswCQYDVQQGEwJUUzENMAsGA1UECAwEVGVzdDENMAsGA1UEBwwEVGVz\n" \
	"dDENMAsGA1UECgwEVGVzdDENMAsGA1UECwwEVGVzdDERMA8GA1UEAwwIZGV2aWNl\n" \
	"MDIxIDAeBgkqhkiG9w0BCQEWEWRldmljZTAyQHRlc3QuY29tMIIBIjANBgkqhkiG\n" \
	"9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0uPNfFqaQXJyWGZTKMivmn2OtRceqich/IKi\n" \
	"aVaCdAYCSqHhqGSJnNx6yQ+tgkGBpwOcWJQXTyxYd8DDzVj+Jm0VlKG4r/UStn4e\n" \
	"5jN8rd4GfqOBl49B2J5lcTiFIJ2A3RsAckqtobMwsILIhpiREVKQLdZcpDXhuGxU\n" \
	"j/QWDSoubhuF9LB84tWhx7OG5BlVBf6QrrnZu1qI7HP1B+jmBV/tE2KaKTR6e8tr\n" \
	"C9GczlwIhHcp59Cca4QBIpFGwkyobBRdVt9Jqg8dOvh/ICMHmQ8GVS6wWGULPddE\n" \
	"WkZgo6IRFPIION/YCCDVwvmf7riLaMhx9HefDdYGnkF9gE52RwIDAQABo1kwVzAf\n" \
	"BgNVHSMEGDAWgBTHF7Ws2B5xIAwucJmvoILEkmKrJTAJBgNVHRMEAjAAMAsGA1Ud\n" \
	"DwQEAwIE8DAcBgNVHREEFTATghFkZXZpY2UwMi50ZXN0LmNvbTANBgkqhkiG9w0B\n" \
	"AQsFAAOCAQEATnvQ2kylZS8IIP6SQHHD01foGNPue+sZyZQ8mTjN+5iFj4O+LGMl\n" \
	"WnIelsJWhUeJo6hIqs4PBe/CcS8Ze7B5/YeVp+qNlXuwE3RQnv/6/6Xak2nucfUc\n" \
	"Ek+rZAtWPuZsKh5ijmzc0R+nFyc07s8d0UGDQVNMrD3y9HvORdb++9FP7Ym5jaze\n" \
	"XloPFyNJ72IbFfnALD3tdeLOLqFIyuqhzu+wYEcTAKJTPyutKSp73aJGC0nVWrR5\n" \
	"riNsFEH7JFDuqcVhLEJMjE1UHV+cLYWVf+6V3t8JXb/tQk9xGDK+/4toQqay0gSx\n" \
	"iMhdRXbtcWIX+64fLIfI/vUkkA+3HolwDQ==\n" \
	"-----END CERTIFICATE-----\n";

const char broan_iotdev_client_key[] =
	"-----BEGIN RSA PRIVATE KEY-----\n" \
	"MIIEpAIBAAKCAQEA0uPNfFqaQXJyWGZTKMivmn2OtRceqich/IKiaVaCdAYCSqHh\n" \
	"qGSJnNx6yQ+tgkGBpwOcWJQXTyxYd8DDzVj+Jm0VlKG4r/UStn4e5jN8rd4GfqOB\n" \
	"l49B2J5lcTiFIJ2A3RsAckqtobMwsILIhpiREVKQLdZcpDXhuGxUj/QWDSoubhuF\n" \
	"9LB84tWhx7OG5BlVBf6QrrnZu1qI7HP1B+jmBV/tE2KaKTR6e8trC9GczlwIhHcp\n" \
	"59Cca4QBIpFGwkyobBRdVt9Jqg8dOvh/ICMHmQ8GVS6wWGULPddEWkZgo6IRFPII\n" \
	"ON/YCCDVwvmf7riLaMhx9HefDdYGnkF9gE52RwIDAQABAoIBAFkc057Bdj9Dihfa\n" \
	"nTc1niZs+dmBvH5v7MeTt+dFG/jE9UDuKLmMSi4TaHr/efT5kzyspOs1IKhe978a\n" \
	"oGJsQXChVaYptC3+I/sjThE+Hmgl0p6+nqsZaNyNChaOqIqAo4xKtaSV88rJOkDL\n" \
	"8soVO++S8MO9ugXVktzoQc9Wd971eKwhosBr0RMclPCWokZqaIfLaW+v3r6OXJ/p\n" \
	"s13hNVeQIF1krwmldNIAEsdX66QrJq/0AbqZYUQ9DdATV2EtyYofitDUIcKQKApg\n" \
	"1OkCURrvaNLf4p8+aB8Abzv4qkCptsNoksfe9RJbKD0C78FzkeONninwedH4bpEi\n" \
	"9V5P9YECgYEA6epECTNbDm2KbIX0PPSK8RwVN+Qg9Wstwbb0osIyH6YQUvRqFHhK\n" \
	"mdQdsNluheGoL08Az3FA5JELZBVhPdn9So4QxboB40+JY48JelemH75hbDv6yLxh\n" \
	"jSKW3F+/ZlReTsHar8wsO535FedW8nxjM+W8S1hRMR+Dv+UPKb2uj0ECgYEA5s0E\n" \
	"HpV5UnoC8g8e4A+zhli2k1Movw4Ypt7D37ZxG8NibIYSMH5MBOD8ByHvZfr1gu5/\n" \
	"UF9Bd5dWMmGfc3qsD52lVF3uQ9tljx/zITOLBUH6Or3kH2DqRWFTqz65BhyIYlma\n" \
	"8bxchZQc1fWVFNlK2xMMlCO16TxBzFDHQYvxK4cCgYEAn5RIkhZNGoy0kNDaDPOw\n" \
	"DklgWF7z9ToHX06XmqntVBYQsOc5r3lZO5SwJMRRWFjYSl4VaXAUG1qwcLj9PBsJ\n" \
	"Z+F/o8UAILlUO22Lw8Ej/if9gr9wmZ2a15QvY2yWwRLxu70YmjIqQwnEsqK+eHNP\n" \
	"okoqqSQ5T8/2K+Xy8EENY4ECgYB+GsaFb2Y6ii/R0jEse2e7n/0hwe4hdbJCerTL\n" \
	"JwPmB3tfkGGf3WHryIHr477KGbTLNUSaxXEfxrByFqTok74vShNrZWcp7FYxPWO6\n" \
	"YE81MDdooRhjjLBz+BmfF0ZA8JYUJqFiM2jaE3Mt9GDgY1ljGaVly505MpNA72Hv\n" \
	"jmbXQQKBgQDZSHQJaUQYX1hRRm04Lz3leMXHGJQZTgTBgGBT7tMhNs6BwppFRUuS\n" \
	"0g9Qf8CT79M3xY66S3xzcA2Ew/tbRYYlnNfb/MaXN+nvNejpNvr6OyyZ9npKeRGf\n" \
	"dPK+ROrvMwK8+yrgmE3KYECuz4QaJRSdvKA4xqj1N2VSE7yLegHuCg==\n" \
	"-----END RSA PRIVATE KEY-----\n";
#else
extern const char broan_iotdev_ca_cert[];
extern const char broan_iotdev_client_cert[];
extern const char broan_iotdev_client_key[];
#endif

#endif /* _CERT_BROAN_IOTDEV_H */